modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gratest_inventions"
version="1.0.0"
displayName="Gratest Inventions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Adam, MCreator"

[[dependencies.gratest_inventions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




